name: Continuously Checking Clean Build

on:
  push:
    paths: "linux"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checking Clean Build
      run: |
        ./install-deps.sh;
        commitSubmodule=$(git rev-parse :linux);
        wget https://github.com/thxxx/linux/archive/${commitSubmodule}.zip;
        unzip -q $commitSubmodule.zip;
        ./build-linux.sh ./linux-$commitSubmodule tinyconfig;
