name: Continuously Checking Clean Build

on:
  push:
    paths: 'linux'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checking Clean Build
      run: |
        ./install-deps.sh;
        commit_number=$(git rev-parse :linux)
        wget https://github.com/thxxx/linux/archive/${{commit_number}}.zip;
        unzip -q ${{commit_number}}.zip;
        ./build-linux.sh ./linux-${{commit_number}} tinyconfig;
