name: TEST

on:
  push:
    paths: 'test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checking Clean Test Case Compilation
      run: |
        make -C test;
